"use client";
import {useMemo,useState} from "react";
import {Search,MapPin,Home,Building2,Landmark,KeyRound,Heart,Plus,ShieldCheck,ChevronRight} from "lucide-react";
const biens=[{id:1,type:"Maison",title:"Maison familiale à PK12",price:"450 000 FCFA / mois",loc:"PK12, Bangui",info:"3 chambres",img:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80"},{id:2,type:"Terrain",title:"Terrain résidentiel 500 m²",price:"12 000 000 FCFA",loc:"Bimbo",info:"500 m²",img:"https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80"},{id:3,type:"Appartement",title:"Appartement moderne centre-ville",price:"350 000 FCFA / mois",loc:"Centre-ville, Bangui",info:"2 chambres",img:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80"}];
export default function Page(){const[q,setQ]=useState("");const[type,setType]=useState("Tous");const[fav,setFav]=useState<number[]>([]);const filtered=useMemo(()=>biens.filter(b=>(type==="Tous"||b.type===type)&&(!q||((b.title+" "+b.loc).toLowerCase().includes(q.toLowerCase())))),[q,type]);return <main>
<header className="bg-white border-b"><div className="container flex items-center justify-between py-4"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-[#10233f] text-[#d8a84e] grid place-items-center font-black">R</div><div><b className="text-xl text-[#10233f]">Immo RCA</b><div className="text-xs text-gray-500">L'immobilier en Centrafrique</div></div></div><nav className="hidden md:flex gap-6 text-sm font-semibold"><a href="#annonces">Annonces</a><a href="#terrains">Terrains</a><a href="#agences">Agences</a><a href="#comment">Comment ça marche</a></nav><button className="btn dark"><KeyRound size={16}/> <span className="ml-2">Se connecter</span></button></div></header>
<section className="hero"><div className="container py-20"><span className="inline-flex gap-2 items-center bg-white/10 rounded-full px-4 py-2 text-sm"><ShieldCheck size={16}/> Annonces immobilières en RCA</span><h1 className="text-4xl md:text-6xl font-black max-w-4xl leading-tight mt-5">Trouvez votre <span className="text-[#d8a84e]">logement, terrain ou local</span> en Centrafrique.</h1><p className="text-white/75 text-lg max-w-2xl mt-5">Recherchez à Bangui et dans les autres villes, puis contactez directement les propriétaires et agences.</p><div className="card mt-8 p-3 grid md:grid-cols-[1fr_180px_auto] gap-3"><div className="flex items-center gap-2 px-3"><Search/><input className="outline-none w-full" placeholder="Quartier, ville, type de bien..." value={q} onChange={e=>setQ(e.target.value)}/></div><select className="input" value={type} onChange={e=>setType(e.target.value)}><option>Tous</option><option>Maison</option><option>Appartement</option><option>Terrain</option></select><button className="btn gold">Rechercher</button></div></div></section>
<section className="container py-10 grid md:grid-cols-4 gap-4"><Stat icon={<Home/>} n="Logements" s="Maisons & appartements"/><Stat icon={<Landmark/>} n="Terrains" s="Parcelles à vendre"/><Stat icon={<Building2/>} n="Locaux" s="Commerces & bureaux"/><Stat icon={<ShieldCheck/>} n="Annonces" s="Infos vérifiables"/></section>
<section id="annonces" className="container pb-16"><div className="flex items-end justify-between mb-6"><div><p className="text-[#d09b35] font-bold">À découvrir</p><h2 className="text-3xl font-black text-[#10233f]">Annonces récentes</h2></div><button className="font-bold flex items-center">Voir tout <ChevronRight size={18}/></button></div><div className="grid md:grid-cols-3 gap-6">{filtered.map(b=><article className="card overflow-hidden" key={b.id}><div className="relative"><img src={b.img} className="w-full h-56 object-cover"/><button onClick={()=>setFav(x=>x.includes(b.id)?x.filter(i=>i!==b.id):[...x,b.id])} className="absolute right-3 top-3 bg-white rounded-full p-3"><Heart size={18} fill={fav.includes(b.id)?"currentColor":"none"}/></button><span className="absolute left-3 bottom-3 bg-[#10233f] text-white rounded-full px-3 py-1 text-xs font-bold">{b.type}</span></div><div className="p-5"><h3 className="font-black text-lg">{b.title}</h3><div className="text-[#d09b35] font-black mt-2">{b.price}</div><div className="text-gray-500 text-sm mt-2 flex items-center gap-1"><MapPin size={15}/>{b.loc} · {b.info}</div><button className="btn dark w-full mt-4">Voir le bien</button></div></article>)}</div></section>
<section id="agences" className="bg-white border-y"><div className="container py-14 grid md:grid-cols-2 gap-10 items-center"><div><p className="text-[#d09b35] font-bold">Pour propriétaires & agences</p><h2 className="text-3xl font-black text-[#10233f]">Publiez votre bien et recevez des demandes.</h2><p className="text-gray-600 mt-3">Photos, prix, localisation, caractéristiques et moyens de contact dans une seule annonce.</p><button className="btn gold mt-5"><Plus size={18}/><span className="ml-2">Publier une annonce</span></button></div><div className="card p-6"><h3 className="font-black text-xl">Catégories Immo RCA</h3><div className="grid grid-cols-2 gap-3 mt-5"><Mini t="Vente" d="Maisons & terrains"/><Mini t="Location" d="Longue durée"/><Mini t="Commercial" d="Bureaux & boutiques"/><Mini t="Terrain" d="Parcelles"/></div></div></div></section>
<section id="comment" className="container py-14"><h2 className="text-3xl font-black text-center text-[#10233f]">Comment ça marche ?</h2><div className="grid md:grid-cols-3 gap-5 mt-8"><Step n="1" t="Recherchez" d="Choisissez une ville, un quartier et un type de bien."/><Step n="2" t="Comparez" d="Consultez photos, prix, surface et informations."/><Step n="3" t="Contactez" d="Appelez ou écrivez au propriétaire ou à l'agence."/></div></section>
<footer className="bg-[#10233f] text-white"><div className="container py-10 flex justify-between"><div><b className="text-2xl">Immo RCA</b><p className="text-white/60">La plateforme immobilière pour la République centrafricaine.</p></div><div className="text-sm text-white/60">© 2026 Immo RCA · Bangui, RCA</div></div></footer></main>}
function Stat({icon,n,s}:{icon:React.ReactNode,n:string,s:string}){return <div className="card p-5 flex items-center gap-4"><div className="p-3 rounded-xl bg-[#f7f1e5] text-[#b47d1c]">{icon}</div><div><div className="font-black">{n}</div><div className="text-xs text-gray-500">{s}</div></div></div>}
function Mini({t,d}:{t:string,d:string}){return <div className="border rounded-xl p-4"><b>{t}</b><div className="text-xs text-gray-500">{d}</div></div>}
function Step({n,t,d}:{n:string,t:string,d:string}){return <div className="card p-6"><div className="w-10 h-10 rounded-full bg-[#d8a84e] grid place-items-center font-black">{n}</div><h3 className="font-black text-xl mt-4">{t}</h3><p className="text-gray-500 mt-2">{d}</p></div>}